/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as LiveInCareRouteImport } from './routes/live-in-care'
import { Route as RequestCareRouteImport } from './routes/request-care'
import { Route as SignInRouteImport } from './routes/sign-in'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveInCareRoute = LiveInCareRouteImport.update({
  id: '/live-in-care',
  path: '/live-in-care',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCareRoute = RequestCareRouteImport.update({
  id: '/request-care',
  path: '/request-care',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/live-in-care': typeof LiveInCareRoute
  '/request-care': typeof RequestCareRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/live-in-care': typeof LiveInCareRoute
  '/request-care': typeof RequestCareRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/live-in-care': typeof LiveInCareRoute
  '/request-care': typeof RequestCareRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/contact'
    | '/create-account'
    | '/live-in-care'
    | '/request-care'
    | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/contact'
    | '/create-account'
    | '/live-in-care'
    | '/request-care'
    | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/contact'
    | '/create-account'
    | '/live-in-care'
    | '/request-care'
    | '/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CreateAccountRoute: typeof CreateAccountRoute
  LiveInCareRoute: typeof LiveInCareRoute
  RequestCareRoute: typeof RequestCareRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-in-care': {
      id: '/live-in-care'
      path: '/live-in-care'
      fullPath: '/live-in-care'
      preLoaderRoute: typeof LiveInCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-care': {
      id: '/request-care'
      path: '/request-care'
      fullPath: '/request-care'
      preLoaderRoute: typeof RequestCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CreateAccountRoute: CreateAccountRoute,
  LiveInCareRoute: LiveInCareRoute,
  RequestCareRoute: RequestCareRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
